/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

import java.math.BigDecimal

/**
 * @param `0` Id of component for example: '''1'''
 * @param `1` The value for example: '''24'''
 * @param `2` Airquality index of this component for example: '''1'''
 * @param `3` Decimal representation of percent in index thresholds. 0.x is between index 0 and 1, 1.x is between index 1 and 2... for example: '''0.25'''
 */
case class AirqualityDateStartCET3AndFollowing (
  `0`: Option[Integer] = None,
  `1`: Option[BigDecimal] = None,
  `2`: Option[Integer] = None,
  `3`: Option[String] = None
)

