/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Date of end of measuring in CET for example: '''2019-02-19 10:00:00'''
 * @param `1` Airquality index for all components for example: '''1'''
 * @param `2` Flag if data is incomplete (not all components available) for example: '''1'''
 * @param `3AndFollowing` Object for component
 */
case class AirqualityDateStartCET (
  `0`: Option[String] = None,
  `1`: Option[Integer] = None,
  `2`: Option[Integer] = None,
  `3AndFollowing`: Option[List[airquality_date start CET_3 and following]] = None
)

