/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Minimum date start (CET) for example: '''2019-02-16 09:00:00'''
 * @param `1` Maximum date start (CET) for example: '''2019-02-19 10:00:00'''
 */
case class AirqualitylimitsStationId (
  `0`: Option[String] = None,
  `1`: Option[String] = None
)

