/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Id of station for example: '''6'''
 * @param `1` Id of component for example: '''3'''
 * @param `2` Year for example: '''2017'''
 * @param `3` value for example: '''35'''
 * @param `4` Id of exceedance type (not used) for example: '''13'''
 */
case class Annualbalance (
  `0`: Option[Integer] = None,
  `1`: Option[Integer] = None,
  `2`: Option[Integer] = None,
  `3`: Option[Integer] = None,
  `4`: Option[Integer] = None
)

