/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Id of component for example: '''5'''
 * @param `1` Component code for example: '''NO2'''
 * @param `2` Component symbol for example: '''NO₂'''
 * @param `3` Component unit for example: '''µg/m³'''
 * @param `4` Components name in specified language for example: '''Nitrogen dioxide'''
 */
case class Component (
  `0`: Option[Integer] = None,
  `1`: Option[String] = None,
  `2`: Option[String] = None,
  `3`: Option[String] = None,
  `4`: Option[String] = None
)

