/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param indices Description of indices for example: '''{"station_id":{"0":"limit date start min (CET)","1":"limit date start max (CET)"}}'''
 * @param data  for example: '''[{"0":"2016-01-01 00:00:00","1":"2019-09-03 11:00:00"}]'''
 */
case class InlineResponse2001 (
  indices: Option[] = None,
  data: Option[List[airqualitylimits]] = None
)

