/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param indices Description of indices for example: '''{"0":"station id,","1":"day_frist,","2":"day_recent,","3":"value of year,","4":"4-15 values of month"}'''
 * @param data 
 */
case class InlineResponse2006 (
  indices: Option[Any] = None,
  data: Option[List[transgression]] = None
)

