/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Id of component for example: '''2'''
 * @param `1` Id of scope for example: '''4'''
 * @param `2` Flag if this combination of component and scope has a map for example: '''1'''
 * @param `3` Flag if this combination of component and scope has an alternative map for example: '''0'''
 * @param `4` Flag if this combination of component and scope is an hourly value for example: '''1'''
 */
case class InlineResponse2007Xref (
  `0`: Option[Integer] = None,
  `1`: Option[Integer] = None,
  `2`: Option[Integer] = None,
  `3`: Option[Integer] = None,
  `4`: Option[Integer] = None
)

