/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param idcode 
 */
case class InlineResponse2003 (
  idcode: Option[component] = None
)

