/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param indices Description of indices for example: '''{"combination of scope id, component id, station id":{"0":"scope id","1":"component id","2":"station id","3":"limit date start min (CET)","4":"limit date start max (CET)"}}'''
 * @param data 
 */
case class InlineResponse2004 (
  indices: Option[Any] = None,
  data: Option[List[inline_response_200_4_data]] = None
)

