/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param components components (available for use = airquality, map, transgression, annualbalance, measure)
 * @param scopes scopes (available for use = airquality, map, measure)
 * @param networks networks (available for use = air quality, transgression, annualbalance, measure)
 * @param stations stations (available for use = airquality, transgression, annualbalance, measure)
 * @param limits1 Limits (available for use = airquality, measure)
 * @param limits2 Limits (available for use = annualbalance)
 * @param xref Cross reference component/scope (available for use = map, measure)
 */
case class InlineResponse2007 (
  components: Option[List[inline_response_200_7_components]] = None,
  scopes: Option[List[inline_response_200_7_scopes]] = None,
  networks: Option[List[inline_response_200_7_networks]] = None,
  stations: Option[List[inline_response_200_7_stations]] = None,
  limits1: Option[List[inline_response_200_7_limits1]] = None,
  limits2: Option[List[inline_response_200_7_limits2]] = None,
  xref: Option[List[inline_response_200_7_xref]] = None
)

