/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param indices Description of indices for example: '''[{"0":"station id"},{"1":"component id"},{"2":"year"},{"3":"value"},{"4":"transgression type"}]'''
 * @param data 
 */
case class InlineResponse2002 (
  indices: Option[List[Any]] = None,
  data: Option[List[annualbalance]] = None
)

