/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param indices Description of indices for example: '''{}'''
 * @param data  for example: '''{"6":{"2019-01-01 00:00:00":{"0":"2019-01-01 01:00:00","1":0,"2":0,"3":{"0":{"0":3,"1":20,"2":0,"3":0.333}}}}}'''
 */
case class InlineResponse200 (
  indices: Option[] = None,
  data: Option[List[airquality]] = None
)

