/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Year for example: '''2004'''
 * @param `1` Id of component for example: '''1'''
 */
case class InlineResponse2007Limits2 (
  `0`: Option[Integer] = None,
  `1`: Option[Integer] = None
)

