/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * The index is a concatination of scope id, component id and station id.
 *
 * @param `0` Id of scope for example: '''1'''
 * @param `1` Id of component for example: '''1'''
 * @param `2` Id of station for example: '''120'''
 * @param `3` Minimum datetime of start (CET) for example: '''2016-01-01T11:00:00.000Z'''
 * @param `4` Maximum datetime of start (CET) for example: '''2019-09-02T11:00:00.000Z'''
 */
case class Limit (
  `0`: Option[String] = None,
  `1`: Option[String] = None,
  `2`: Option[String] = None,
  `3`: Option[String] = None,
  `4`: Option[String] = None
)

