/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

import java.math.BigDecimal

/**
 * @param `0` Id of component for example: '''2'''
 * @param `1` Id of scope for example: '''2'''
 * @param `2` Value of measurement for example: '''112.4'''
 * @param `3` Date end (CET) for example: '''2019-01-01 02:00:00'''
 * @param `4` Air quality index for example: '''1'''
 */
case class Measure (
  `0`: Option[Integer] = None,
  `1`: Option[Integer] = None,
  `2`: Option[BigDecimal] = None,
  `3`: Option[String] = None,
  `4`: Option[Integer] = None
)

