/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Id of network for example: '''2'''
 * @param `1` Network short code for example: '''BY'''
 * @param `2` Networks name in specified language for example: '''Bavaria'''
 */
case class Network (
  `0`: Option[Integer] = None,
  `1`: Option[String] = None,
  `2`: Option[String] = None
)

