/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Id of scope for example: '''2'''
 * @param `1` Scope code for example: '''1SMW'''
 * @param `2` Scope time base for example: '''hour'''
 * @param `3` Scope time scope for example: '''3600'''
 * @param `4` Scope time is max for example: '''0'''
 * @param `5` Scope name in specified language for example: '''1-hour average'''
 */
case class Scope (
  `0`: Option[Integer] = None,
  `1`: Option[String] = None,
  `2`: Option[String] = None,
  `3`: Option[Integer] = None,
  `4`: Option[Integer] = None,
  `5`: Option[String] = None
)

