/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Id of station type for example: '''2'''
 * @param `1` Name of station type in specified language for example: '''industry'''
 */
case class Stationtype (
  `0`: Option[Integer] = None,
  `1`: Option[String] = None
)

