/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Id of station for example: '''769'''
 * @param `1` Code of station for example: '''DEHH016'''
 * @param `2` Name of station for example: '''Hamburg Billbrook'''
 * @param `3` City of station for example: '''Hamburg'''
 * @param `4` Synonym of station for example: '''21BI'''
 * @param `5` Date of first activity for example: '''1985-01-01T00:00:00.000Z'''
 * @param `6` Date of last activity (null when still running) for example: '''1985-01-01T00:00:00.000Z'''
 * @param `7` Longitude of station for example: '''10.0817'''
 * @param `8` Latitude of station for example: '''53.529'''
 * @param `9` Id of network for example: '''6'''
 * @param `10` Id of station setting for example: '''1'''
 * @param `11` Id of station type for example: '''2'''
 * @param `12` Code of network for example: '''HH'''
 * @param `13` Name of network in specified language for example: '''Hamburg'''
 * @param `14` Name of station setting in specified language for example: '''urban area'''
 * @param `15` Short name of station setting in specified language for example: '''urban'''
 * @param `16` Name of station type in specified language for example: '''industry'''
 * @param `17` Street of station for example: '''Lauchhammerstr.'''
 * @param `18` Street number of station for example: '''23'''
 * @param `19` ZIP code of station for example: '''04910'''
 */
case class Station (
  `0`: Option[String] = None,
  `1`: Option[String] = None,
  `2`: Option[String] = None,
  `3`: Option[String] = None,
  `4`: Option[String] = None,
  `5`: Option[String] = None,
  `6`: Option[String] = None,
  `7`: Option[String] = None,
  `8`: Option[String] = None,
  `9`: Option[String] = None,
  `10`: Option[String] = None,
  `11`: Option[String] = None,
  `12`: Option[String] = None,
  `13`: Option[String] = None,
  `14`: Option[String] = None,
  `15`: Option[String] = None,
  `16`: Option[String] = None,
  `17`: Option[String] = None,
  `18`: Option[String] = None,
  `19`: Option[String] = None
)

