/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Id of threshold for example: '''5'''
 * @param `1` Id of component for example: '''5'''
 * @param `2` Id of scope for example: '''1'''
 * @param `3` Threshold minimum value for example: '''201'''
 * @param `4` Threshold maximum value for example: '''1000'''
 * @param `5` Threshold index for example: '''4'''
 */
case class Threshold (
  `0`: Option[Integer] = None,
  `1`: Option[Integer] = None,
  `2`: Option[Integer] = None,
  `3`: Option[Integer] = None,
  `4`: Option[Integer] = None,
  `5`: Option[Integer] = None
)

