/**
 * Umweltbundesamt Air Data API
 * Air data API of Umweltbundesamt
 *
 * OpenAPI spec version: 2.0.1
 * Contact: immission@uba.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package model

/**
 * @param `0` Id of station for example: '''2'''
 * @param `1` Date of first activity for example: '''2019-01-01'''
 * @param `2` Date of recent activity for example: '''2019-01-01'''
 * @param `3` Sum of values of year for example: '''24'''
 * @param `4` Value of January for example: '''2'''
 * @param `5` Value of Feburary for example: '''2'''
 * @param `6` Value of March for example: '''2'''
 * @param `7` Value of April for example: '''2'''
 * @param `8` Value of May for example: '''2'''
 * @param `9` Value of June for example: '''2'''
 * @param `10` Value of July for example: '''2'''
 * @param `11` Value of August for example: '''2'''
 * @param `12` Value of September for example: '''2'''
 * @param `13` Value of October for example: '''2'''
 * @param `14` Value of November for example: '''2'''
 * @param `15` Value of December for example: '''2'''
 */
case class Transgression (
  `0`: Option[Integer] = None,
  `1`: Option[String] = None,
  `2`: Option[String] = None,
  `3`: Option[Integer] = None,
  `4`: Option[Integer] = None,
  `5`: Option[Integer] = None,
  `6`: Option[Integer] = None,
  `7`: Option[Integer] = None,
  `8`: Option[Integer] = None,
  `9`: Option[Integer] = None,
  `10`: Option[Integer] = None,
  `11`: Option[Integer] = None,
  `12`: Option[Integer] = None,
  `13`: Option[Integer] = None,
  `14`: Option[Integer] = None,
  `15`: Option[Integer] = None
)

